<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="wangmengleideMacBook-Pro.local" ignored="0" name="有坏的哦content测试" tests="3" failures="1" timestamp="19 九月 2018 18:07:03 GMT" time="0.01" errors="0">
  <testcase name="TestArtical1" time="0.001" classname="com.job.ui.contentmanager.cont1"/>
  <testcase name="TestArtical1" time="0.001" classname="com.job.ui.contentmanager.cont2"/>
  <testcase name="ys" time="0.003" classname="com.job.ui.contentmanager.con3">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.job.ui.contentmanager.con3.ys(con3.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ys -->
</testsuite> <!-- 有坏的哦content测试 -->
